# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_tutorial',
                'doc_host': 'https://yonatan-bw.github.io',
                'git_url': 'https://github.com/yonatan-bw/nbdev_tutorial',
                'lib_path': 'nbdev_tutorial'},
  'syms': { 'nbdev_tutorial.card': { 'nbdev_tutorial.card.Card': ('card.html#card', 'nbdev_tutorial/card.py'),
                                     'nbdev_tutorial.card.Card.__eq__': ('card.html#card.__eq__', 'nbdev_tutorial/card.py'),
                                     'nbdev_tutorial.card.Card.__gt__': ('card.html#card.__gt__', 'nbdev_tutorial/card.py'),
                                     'nbdev_tutorial.card.Card.__init__': ('card.html#card.__init__', 'nbdev_tutorial/card.py'),
                                     'nbdev_tutorial.card.Card.__lt__': ('card.html#card.__lt__', 'nbdev_tutorial/card.py'),
                                     'nbdev_tutorial.card.Card.__str__': ('card.html#card.__str__', 'nbdev_tutorial/card.py')},
            'nbdev_tutorial.core': {'nbdev_tutorial.core.foo': ('core.html#foo', 'nbdev_tutorial/core.py')}}}
